puts "Seeding Abilities..."

abilities = [
    {
        name: "Weapon Attack",
        key: "weapon_attack",
        passive: false,
        element: Element.find_by(key: "null"),
        cost: 0,
        ability_type: "simple", # "simple" | "skills" | "magic"
        potency: 1,
        range: 1,
        level: 1,
        group: "basic_actions",
        icon: VisualRender.find_by(name: "icon_placeholder"),
        level_requirement: 1,
        description: "A basic attack using a weapon. Deals 100% weapon damage + 100% strength modifier damage.",
        usable_outside_combat: false,
        ability_key: "use_offensive_skill",
    },
    {
        name: "Defend",
        key: "defend",
        passive: false,
        element: Element.find_by(key: "null"),
        cost: 0,
        ability_type: "simple", # "simple" | "skills" | "magic"
        potency: 0.5, # Reduces damage taken by 50%
        range: 1,
        level: 1,
        group: "basic_actions",
        icon: VisualRender.find_by(name: "icon_placeholder"),
        level_requirement: 1,
        description: "A basic defensive action that reduces incoming damage by 50% for one turn.",
        usable_outside_combat: false,
        ability_key: "basic_defense",
    },
    {
        name: "Skills",
        key: "skills",
        passive: false,
        element: Element.find_by(key: "null"),
        cost: 0,
        ability_type: "simple", # "simple" | "skills" | "magic"
        potency: 1,
        range: 1,
        level: 1,
        group: "basic_actions",
        icon: VisualRender.find_by(name: "icon_placeholder"),
        level_requirement: 1,
        description: "Attempt to use a skill.",
        usable_outside_combat: false,
        ability_key: "use_vocation_skills",
    },
    {
        name: "Magic",
        key: "magic",
        passive: false,
        element: Element.find_by(key: "null"),
        cost: 0,
        ability_type: "simple", # "simple" | "skills" | "magic"
        potency: 1,
        range: 1,
        level: 1,
        group: "basic_actions",
        icon: VisualRender.find_by(name: "icon_placeholder"),
        level_requirement: 1,
        description: "Attempt to cast a spell.",
        usable_outside_combat: false,
        ability_key: "use_vocation_magic",
    },
    {
        name: "Use Item",
        key: "use_item",
        passive: false,
        element: Element.find_by(key: "null"),
        cost: 0,
        ability_type: "simple", # "simple" | "skills" | "magic"
        potency: 1,
        range: 1,
        level: 1,
        group: "basic_actions",
        icon: VisualRender.find_by(name: "icon_placeholder"),
        level_requirement: 1,
        description: "Attempt to use an item.",
        usable_outside_combat: false,
        ability_key: "use_inventory_items",
    },
    {
        name: "Flee",
        key: "flee",
        passive: false,
        element: Element.find_by(key: "null"),
        cost: 0,
        ability_type: "simple", # "simple" | "skills" | "magic"
        potency: 1,
        range: 1,
        level: 1,
        group: "basic_actions",
        icon: VisualRender.find_by(name: "icon_placeholder"),
        level_requirement: 1,
        description: "A basic action to attempt to escape from combat.",
        usable_outside_combat: false,
        ability_key: "flee",
    },
    {
        name: "Power Attack",
        key: "power_attack",
        passive: false,
        element: Element.find_by(key: "null"),
        cost: 1,
        ability_type: "skills", # "simple" | "skills" | "magic"
        potency: 1.5,
        range: 1,
        level: 1,
        group: "physical_attacks",
        icon: VisualRender.find_by(name: "icon_placeholder"),
        level_requirement: 1,
        description: "A stronger single target atttack that deals 150% weapon damage + 150% strength modifier damage.",
        usable_outside_combat: false,
        ability_key: "use_offensive_skill",
    },
    {
        name: "Full Swing",
        key: "full_swing",
        passive: false,
        element: Element.find_by(key: "null"),
        cost: 2,
        ability_type: "skills", # "simple" | "skills" | "magic"
        potency: 0.5,
        range: 1,
        level: 1,
        group: "physical_attacks",
        icon: VisualRender.find_by(name: "icon_placeholder"),
        level_requirement: 1,
        description: "A wide reaching attack that hits all enemies in melee range, dealing 50% weapon damage + 50% strength modifier damage to each.",
        usable_outside_combat: false,
        ability_key: "use_offensive_skill",
    },
    {
        name: "Hide",
        key: "hide",
        passive: false,
        element: Element.find_by(key: "null"),
        cost: 1,
        ability_type: "skills", # "simple" | "skills" | "magic"
        potency: 0.5,
        range: 1,
        level: 1,
        group: "special_action",
        icon: VisualRender.find_by(name: "icon_placeholder"),
        level_requirement: 1,
        description: "Attempt to hide in shadows, making it harder for enemies to target you. If successful, you gain a stealth bonus that increases your evasion and reduces the chance of being hit by enemy attacks.",
        usable_outside_combat: false,
        ability_key: "use_skill_hide",
    },
    {
        name: "Sneak Attack",
        key: "sneak_attack",
        passive: false,
        element: Element.find_by(key: "null"),
        cost: 1,
        ability_type: "skills", # "simple" | "skills" | "magic"
        potency: 2,
        range: 1,
        level: 1,
        group: "special_action",
        icon: VisualRender.find_by(name: "icon_placeholder"),
        level_requirement: 1,
        description: "Attack from the shadows, dealing double damage to an unsuspecting target.",
        usable_outside_combat: false,
        ability_key: "use_skill_sneak_attack",
    },
    {
        name: "Steal",
        key: "steal",
        passive: false,
        element: Element.find_by(key: "null"),
        cost: 1,
        ability_type: "skills", # "simple" | "skills" | "magic"
        potency: 0.3,
        range: 1,
        level: 1,
        group: "special_action",
        icon: VisualRender.find_by(name: "icon_placeholder"),
        level_requirement: 1,
        description: "Try to steal an item from an enemy.",
        usable_outside_combat: false,
        ability_key: "use_skill_steal",
    },
    {
        name: "Fire Bolt",
        key: "fire_bolt",
        passive: false,
        element: Element.find_by(key: "fire"),
        cost: 1,
        ability_type: "magic", # "simple" | "skills" | "magic"
        potency: 1,
        range: 1,
        level: 1,
        group: "elemental_magic",
        icon: VisualRender.find_by(name: "icon_placeholder"),
        level_requirement: 1,
        description: "A magical fire attack that hits a single target, dealing spell damage based on the caster's intelligence and the target's resistance to fire with a chance to ignite the target, causing additional damage over time.",
        usable_outside_combat: false,
        ability_key: "use_offensive_skill",
    },
    {
        name: "Water Bolt",
        key: "water_bolt",
        passive: false,
        element: Element.find_by(key: "water"),
        cost: 1,
        ability_type: "magic", # "simple" | "skills" | "magic"
        potency: 1,
        range: 1,
        level: 1,
        group: "elemental_magic",
        icon: VisualRender.find_by(name: "icon_placeholder"),
        level_requirement: 2,
        description: "A magical water attack that hits a single target, dealing spell damage based on the caster's intelligence and the target's resistance to water with a chance to slow the target, reducing their speed for a short duration.",
        usable_outside_combat: false,
        ability_key: "use_offensive_skill",
    },
    {
        name: "Earth Bolt",
        key: "earth_bolt",
        passive: false,
        element: Element.find_by(key: "earth"),
        cost: 1,
        ability_type: "magic", # "simple" | "skills" | "magic"
        potency: 1,
        range: 1,
        level: 1,
        group: "elemental_magic",
        icon: VisualRender.find_by(name: "icon_placeholder"),
        level_requirement: 3,
        description: "A magical earth attack that hits a single target, dealing spell damage based on the caster's intelligence and the target's resistance to earth with a chance to stun the target, making them unable to act for one or more turns.",
        usable_outside_combat: false,
        ability_key: "use_offensive_skill",
    },
    {
        name: "Lightning Bolt",
        key: "lightning_bolt",
        passive: false,
        element: Element.find_by(key: "lightning"),
        cost: 1,
        ability_type: "magic", # "simple" | "skills" | "magic"
        potency: 1,
        range: 1,
        level: 1,
        group: "elemental_magic",
        icon: VisualRender.find_by(name: "icon_placeholder"),
        level_requirement: 4,
        description: "A magical lightning attack that hits a single target, dealing spell damage based on the caster's intelligence and the target's resistance to lightning with a chance to paralyze the target, which may prevent them from moving for a few turns.",
        usable_outside_combat: false,
        ability_key: "use_offensive_skill",
    },
    {
        name: "Heal",
        key: "heal",
        passive: false,
        element: Element.find_by(key: "light"),
        cost: 1,
        ability_type: "magic", # "simple" | "skills" | "magic"
        potency: 1,
        range: 1,
        level: 1,
        group: "elemental_magic",
        icon: VisualRender.find_by(name: "icon_placeholder"),
        level_requirement: 1,
        description: "A spell that restores a small amount of hit points to a target, based on the caster's wisdom.",
        usable_outside_combat: true,
        ability_key: "use_defensive_skill",
    },
    {
        name: "Cure",
        key: "cure",
        passive: false,
        element: Element.find_by(key: "light"),
        cost: 1,
        ability_type: "magic", # "simple" | "skills" | "magic"
        potency: 1,
        range: 1,
        level: 1,
        group: "elemental_magic",
        icon: VisualRender.find_by(name: "icon_placeholder"),
        level_requirement: 2,
        description: "A spell that cures a status effect from a target, such as poison or stun.",
        usable_outside_combat: true,
        ability_key: "use_defensive_skill",
    },
]

abilities.each do |ability|
    Ability.find_or_create_by!(ability)
    puts "Created ability: #{ability[:name]}"
end

puts "Seeding Abilities completed!"