puts "Seeding Items..."

items = [
    {  
        name: "Dagger",
        valuable: false, 
        usable: false, 
        worth: 10, 
        rarity: 50.0,
        attack_value: [1,4].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_dagger'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'right_hand_one'),
        description: "A short blade."
    },
    {  
        name: "Short Sword",
        valuable: false, 
        usable: false, 
        worth: 20, 
        rarity: 50.0,
        attack_value: [1,6].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_short_sword'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'right_hand_one'),
        description: "A short sword." 
    },
    {  
        name: "Longsword",
        valuable: false, 
        usable: false, 
        worth: 50, 
        rarity: 40.0,
        attack_value: [1,8].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_longsword'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'right_hand_one'),
        description: "A long sword." 
    },
    {  
        name: "Greatsword",
        valuable: false, 
        usable: false, 
        worth: 100, 
        rarity: 30.0,
        attack_value: [1,12].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_greatsword'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'right_hand_one'),
        description: "A two handed great sword.",
        twohanded: true
    },
    {  
        name: "Mace",
        valuable: false, 
        usable: false, 
        worth: 30, 
        rarity: 50.0,
        attack_value: [2,6].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_mace'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'right_hand_one'),
        description: "A blunt weapon." 
    },
    {  
        name: "Great Hammer",
        valuable: false, 
        usable: false, 
        worth: 60, 
        rarity: 30.0,
        attack_value: [2,10].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_great_hammer'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'right_hand_one'),
        description: "A giant hammer.",
        twohanded: true
    },
    {  
        name: "Hand Axe",
        valuable: false, 
        usable: false, 
        worth: 40, 
        rarity: 50.0,
        attack_value: [1,6].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_hand_axe'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'right_hand_one'),
        description: "A blunt weapon." 
    },
    {  
        name: "Greataxe",
        valuable: false, 
        usable: false, 
        worth: 80, 
        rarity: 30.0,
        attack_value: [1,14].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_greataxe'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'right_hand_one'),
        description: "A giant axe.",
        twohanded: true
    },
    {  
        name: "Staff",
        valuable: false, 
        usable: false, 
        worth: 10, 
        rarity: 50.0,
        attack_value: [1,6].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_staff'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'right_hand_one'),
        description: "A long stick.",
        twohanded: true
    },
    {  
        name: "Spear",
        valuable: false, 
        usable: false, 
        worth: 20, 
        rarity: 50.0,
        attack_value: [1,8].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_spear'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'right_hand_one'),
        description: "A stick with a sharp bladed metal tip.",
        twohanded: true
    },
    {  
        name: "Halberd",
        valuable: false, 
        usable: false, 
        worth: 100,
        rarity: 30.0, 
        attack_value: [1,12].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_halberd'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'right_hand_one'),
        description: "A giant pole axe with a sharp tip.",
        twohanded: true
    },
    {  
        name: "Leather Cap",
        valuable: false, 
        usable: false, 
        worth: 20,
        rarity: 50.0, 
        attack_value: [0,0].to_json, 
        defensive_value: [1,1].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_leather_cap'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'head'),
        description: "A simple hat made of leather.",
    },
    {  
        name: "Light Helm",
        valuable: false, 
        usable: false, 
        worth: 50,
        rarity: 50.0, 
        attack_value: [0,0].to_json, 
        defensive_value: [2,2].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_light_helm'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'head'),
        description: "A simple helmet made of thin metal.",
    },
    {  
        name: "Chain Coif",
        valuable: false, 
        usable: false, 
        worth: 80,
        rarity: 30.0, 
        attack_value: [0,0].to_json, 
        defensive_value: [3,3].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_chain_coif'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'head'),
        description: "A hood made with chain mail.",
    },
    {  
        name: "Plate Helm",
        valuable: false, 
        usable: false, 
        worth: 120,
        rarity: 10.0, 
        attack_value: [0,0].to_json, 
        defensive_value: [4,4].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_plate_helm'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'head'),
        description: "A heavy helmet made with thick plates of metal.",
    },
    {  
        name: "Linen Cloth",
        valuable: false, 
        usable: false, 
        worth: 10,
        rarity: 60.0, 
        attack_value: [0,0].to_json, 
        defensive_value: [1,1].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_linen_cloth'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'body'),
        description: "A light cloth armor.",
    },
    {  
        name: "Leather Armor",
        valuable: false, 
        usable: false, 
        worth: 40,
        rarity: 40.0, 
        attack_value: [0,0].to_json, 
        defensive_value: [2,2].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_leather_armor'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'body'),
        description: "A light leather armor.",
    },
    {  
        name: "Chain Mail Shirt",
        valuable: false, 
        usable: false, 
        worth: 80,
        rarity: 30.0, 
        attack_value: [0,0].to_json, 
        defensive_value: [4,4].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_chain_mail_shirt'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'body'),
        description: "A light mail made of small chain links.",
    },
    {  
        name: "Scale Mail",
        valuable: false, 
        usable: false, 
        worth: 120,
        rarity: 15.0, 
        attack_value: [0,0].to_json, 
        defensive_value: [5,5].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_scale_mail'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'body'),
        description: "A light mail made of small metal plates.",
    },
    {  
        name: "Plate Mail",
        valuable: false, 
        usable: false, 
        worth: 200,
        rarity: 5.0, 
        attack_value: [0,0].to_json, 
        defensive_value: [8,8].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_plate_mail'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'body'),
        description: "A heavy suit of armor made with thick metal plates.",
    },
    {  
        name: "Buckler",
        valuable: false, 
        usable: false, 
        worth: 10,
        rarity: 50.0, 
        attack_value: [0,0].to_json, 
        defensive_value: [1,1].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_buckler'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'left_hand_one'),
        description: "A small round disc that barely covers your forearm.",
    },
    {  
        name: "Light Shield",
        valuable: false, 
        usable: false, 
        worth: 50,
        rarity: 30.0, 
        attack_value: [0,0].to_json, 
        defensive_value: [2,2].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_light_shield'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'left_hand_one'),
        description: "A small wooden shield.",
    },
    {  
        name: "Kite Shield",
        valuable: false, 
        usable: false, 
        worth: 80,
        rarity: 20.0, 
        attack_value: [0,0].to_json, 
        defensive_value: [3,3].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_kite_shield'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'left_hand_one'),
        description: "A sturdy metal shield.",
    },
    {  
        name: "Heavy Shield",
        valuable: false, 
        usable: false, 
        worth: 80,
        rarity: 15.0, 
        attack_value: [0,0].to_json, 
        defensive_value: [4,4].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_heavy_shield'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'left_hand_one'),
        description: "A large shield.",
    },
    {  
        name: "Tower Shield",
        valuable: false, 
        usable: false, 
        worth: 150,
        rarity: 5.0, 
        attack_value: [0,0].to_json, 
        defensive_value: [5,5].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_tower_shield'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'left_hand_one'),
        description: "A massive shield.",
    },
    {  
        name: "Silver Ring",
        valuable: false, 
        usable: false, 
        worth: 50,
        rarity: 30.0, 
        attack_value: [0,0].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_silver_ring'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'left_ring'),
        description: "A small ring made of silver.",
    },
    {  
        name: "Gold Ring",
        valuable: false, 
        usable: false, 
        worth: 150,
        rarity: 10.0, 
        attack_value: [0,0].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_gold_ring'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'left_ring'),
        description: "A small ring made of gold.",
    },
    {  
        name: "Diamond Ring",
        valuable: false, 
        usable: false, 
        worth: 500,
        rarity: 5.0, 
        attack_value: [0,0].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_diamond_ring'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'left_ring'),
        description: "A small ring made of diamond.",
    },
    {  
        name: "Short Bow",
        valuable: false, 
        usable: false, 
        worth: 30, 
        rarity: 40.0,
        attack_value: [1,4].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_short_bow'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'right_hand_one'),
        description: "A simple bow.",
        twohanded: true
    },
    {  
        name: "Long Bow",
        valuable: false, 
        usable: false, 
        worth: 50, 
        rarity: 30.0,
        attack_value: [1,6].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_long_bow'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'right_hand_one'),
        description: "A tall wooden bow.",
        twohanded: true
    },
    {  
        name: "Mandate of Heaven",
        valuable: false, 
        usable: false, 
        worth: 1, 
        rarity: 1.0,
        attack_value: [10,40].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_mandate_of_Heaven'),
        element: Element.find_by(key: 'null'),
        template: true,
        equippable_slot: EquippableSlot.find_by(key: 'right_hand_one'),
        description: "Royal Edict." 
    },
    {
        name: "Potion of Greater Healing",
        valuable: false, 
        usable: true, 
        worth: 300, 
        rarity: 5.0,
        attack_value: [12,32].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_potion_of_greater_healing'),
        element: Element.find_by(key: 'null'),
        template: true,
        description: "A potion that restores a large amount of health."
    },
    {
        name: "Potion of Healing",
        valuable: false, 
        usable: true, 
        worth: 100, 
        rarity: 15.0,
        attack_value: [6,16].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_potion_of_healing'),
        element: Element.find_by(key: 'null'),
        template: true,
        description: "A potion that restores a moderate amount of health."
    },
    {
        name: "Herb",
        valuable: false, 
        usable: true, 
        worth: 30, 
        rarity: 30.0,
        attack_value: [1,5].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_herb'),
        element: Element.find_by(key: 'null'),
        template: true,
        description: "A healing herb that restores a small amount of health."
    },
    {
        name: "Panacea",
        valuable: false, 
        usable: true, 
        worth: 50, 
        rarity: 10.0,
        attack_value: [1,1].to_json, 
        defensive_value: [0,0].to_json, 
        potency: 1,
        visual_render: VisualRender.find_by(name: 'item_panacea'),
        element: Element.find_by(key: 'null'),
        template: true,
        description: "A mixture that cures all ailments."
    },
]

items.each do |item|
    Item.find_or_create_by!(item)
    puts "Created item: #{item[:name]}"
end

puts "Seeding Items completed!"