puts "Seeding Monster templates..."

monster_templates = [
    {
        name: "Goblin",
        vocation: Vocation.find_by(name: "Warrior"),
        race: Race.find_by(key: "human"),
        visual_render: VisualRender.find_by(name: "monster_goblin"),
        element: Element.find_by(key: "earth"),
        level: 1,
        experience_points: 0,
        hit_points: 4,
        power_points: 10,
        max_hit_points: 4,
        max_power_points: 10,
        strength: 3,
        dexterity: 3,
        constitution: 2,
        intelligence: 2,
        wisdom: 2,
        charisma: 1,
        template: true,
        description: "A small, green-skinned humanoid creature, wielding crude weapons with cunning and feral aggression.",
        threat: 1.0,
    },
    {
        name: "Goblin Warrior",
        vocation: Vocation.find_by(name: "Warrior"),
        race: Race.find_by(key: "human"),
        visual_render: VisualRender.find_by(name: "monster_goblin_warrior"),
        element: Element.find_by(key: "earth"),
        level: 1,
        experience_points: 0,
        hit_points: 6,
        power_points: 16,
        max_hit_points: 6,
        max_power_points: 16,
        strength: 4,
        dexterity: 4,
        constitution: 3,
        intelligence: 2,
        wisdom: 2,
        charisma: 1,
        template: true,
        description: "A small, green-skinned fighter clad in ragged armor, wielding crude weapons with cunning and feral aggression.",
        threat: 2.0,
    },
    {
        name: "Orc",
        vocation: Vocation.find_by(name: "Warrior"),
        race: Race.find_by(key: "human"),
        visual_render: VisualRender.find_by(name: "monster_orc"),
        element: Element.find_by(key: "earth"),
        level: 1,
        experience_points: 0,
        hit_points: 12,
        power_points: 20,
        max_hit_points: 12,
        max_power_points: 20,
        strength: 6,
        dexterity: 3,
        constitution: 6,
        intelligence: 2,
        wisdom: 2,
        charisma: 1,
        template: true,
        description: "A large, green-skinned warrior clad in hide armor, wielding crude weapons with cunning and feral aggression.",
        threat: 4.0,
    },
    {
        name: "Skeleton",
        vocation: Vocation.find_by(name: "Warrior"),
        race: Race.find_by(key: "human"),
        visual_render: VisualRender.find_by(name: "monster_skeleton"),
        element: Element.find_by(key: "darkness"),
        level: 1,
        experience_points: 0,
        hit_points: 8,
        power_points: 16,
        max_hit_points: 8,
        max_power_points: 16,
        strength: 5,
        dexterity: 3,
        constitution: 4,
        intelligence: 2,
        wisdom: 2,
        charisma: 1,
        template: true,
        description: "An undead creature of bleached bones clad in tattered armor, wielding rusted weapons with relentless, unholy resolve.",
        threat: 2.0,
    },
    {
        name: "Skeleton Warrior",
        vocation: Vocation.find_by(name: "Warrior"),
        race: Race.find_by(key: "human"),
        visual_render: VisualRender.find_by(name: "monster_skeleton_warrior"),
        element: Element.find_by(key: "darkness"),
        level: 1,
        experience_points: 0,
        hit_points: 12,
        power_points: 20,
        max_hit_points: 12,
        max_power_points: 20,
        strength: 6,
        dexterity: 5,
        constitution: 4,
        intelligence: 2,
        wisdom: 2,
        charisma: 1,
        template: true,
        description: "An undead fighter of bleached bones clad in rusted ancient armor, wielding rusted weapons with relentless, unholy resolve.",
        threat: 3.0,
    },
    {
        name: "Zombie",
        vocation: Vocation.find_by(name: "Warrior"),
        race: Race.find_by(key: "human"),
        visual_render: VisualRender.find_by(name: "monster_zombie"),
        element: Element.find_by(key: "darkness"),
        level: 1,
        experience_points: 0,
        hit_points: 10,
        power_points: 10,
        max_hit_points: 10,
        max_power_points: 10,
        strength: 5,
        dexterity: 1,
        constitution: 5,
        intelligence: 1,
        wisdom: 1,
        charisma: 1,
        template: true,
        description: "A reanimated corpse driven by an insatiable hunger for the living.",
        threat: 2.0,
    },
    {
        name: "Ghost",
        vocation: Vocation.find_by(name: "Scholar"),
        race: Race.find_by(key: "human"),
        visual_render: VisualRender.find_by(name: "monster_ghost"),
        element: Element.find_by(key: "darkness"),
        level: 1,
        experience_points: 0,
        hit_points: 10,
        power_points: 30,
        max_hit_points: 10,
        max_power_points: 30,
        strength: 3,
        dexterity: 5,
        constitution: 3,
        intelligence: 6,
        wisdom: 2,
        charisma: 1,
        template: true,
        description: "The restless spirit of the dead, drifting between worlds in ethereal silence.",
        threat: 3.5,
    },
    {
        name: "Wolf",
        vocation: Vocation.find_by(name: "Warrior"),
        race: Race.find_by(key: "human"),
        visual_render: VisualRender.find_by(name: "monster_wolf"),
        element: Element.find_by(key: "null"),
        level: 1,
        experience_points: 0,
        hit_points: 8,
        power_points: 16,
        max_hit_points: 8,
        max_power_points: 16,
        strength: 4,
        dexterity: 5,
        constitution: 3,
        intelligence: 2,
        wisdom: 2,
        charisma: 1,
        template: true,
        description: "A fierce, cunning predator that hunts in loyal packs under the moonlight.",
        threat: 2.0,
    },
    {
        name: "Imp",
        vocation: Vocation.find_by(name: "Scholar"),
        race: Race.find_by(key: "human"),
        visual_render: VisualRender.find_by(name: "monster_imp"),
        element: Element.find_by(key: "darkness"),
        level: 1,
        experience_points: 0,
        hit_points: 14,
        power_points: 30,
        max_hit_points: 14,
        max_power_points: 30,
        strength: 6,
        dexterity: 6,
        constitution: 6,
        intelligence: 8,
        wisdom: 4,
        charisma: 2,
        template: true,
        description: "A small, mischievous demon that delights in trickery and chaos.",
        threat: 4.0,
    },
    {
        name: "Stone Golem",
        vocation: Vocation.find_by(name: "Warrior"),
        race: Race.find_by(key: "human"),
        visual_render: VisualRender.find_by(name: "monster_stone_golem"),
        element: Element.find_by(key: "earth"),
        level: 1,
        experience_points: 0,
        hit_points: 20,
        power_points: 20,
        max_hit_points: 20,
        max_power_points: 20,
        strength: 8,
        dexterity: 2,
        constitution: 8,
        intelligence: 1,
        wisdom: 1,
        charisma: 1,
        template: true,
        description: "A towering construct of rock, animated by ancient magic to guard and destroy.",
        threat: 5.0,
    },
    {
        name: "Slime",
        vocation: Vocation.find_by(name: "Warrior"),
        race: Race.find_by(key: "human"),
        visual_render: VisualRender.find_by(name: "monster_slime"),
        element: Element.find_by(key: "null"),
        level: 1,
        experience_points: 0,
        hit_points: 5,
        power_points: 10,
        max_hit_points: 5,
        max_power_points: 10,
        strength: 3,
        dexterity: 4,
        constitution: 3,
        intelligence: 1,
        wisdom: 1,
        charisma: 1,
        template: true,
        description: "A gelatinous creature that engulfs and dissolves anything in its path.",
        threat: 1.0,
    },
    {
        name: "Dragon",
        vocation: Vocation.find_by(name: "Scholar"),
        race: Race.find_by(key: "human"),
        visual_render: VisualRender.find_by(name: "monster_dragon"),
        element: Element.find_by(key: "fire"),
        level: 1,
        experience_points: 0,
        hit_points: 30,
        power_points: 50,
        max_hit_points: 30,
        max_power_points: 50,
        strength: 8,
        dexterity: 8,
        constitution: 8,
        intelligence: 10,
        wisdom: 8,
        charisma: 6,
        template: true,
        description: "A massive, fire-breathing tyrant whose greed and wrath scorch the land.",
        threat: 8.0,
    },
]

monster_templates.each do |monster_template|
    Character.find_or_create_by!(monster_template)
    puts "Created monster template: #{monster_template[:name]}"
end

puts "Seeding Monster templates completed!"