puts "Seeding Visual Renders..."

images = [
    { name: "icon_placeholder", url: "---" },
    { name: "male_human_1", url: "/images/characters/male-human.png", visual_type: "character" },
    { name: "male_human_2", url: "/images/characters/male-human-2.png", visual_type: "character" },
    { name: "male_human_3", url: "/images/characters/male-human-3.png", visual_type: "character" },
    { name: "male_dwarf_1", url: "/images/characters/male-dwarf.png", visual_type: "character" },
    { name: "male_elf_1", url: "/images/characters/male-elf.png", visual_type: "character" },
    { name: "male_orc_1", url: "/images/characters/male-orc.png", visual_type: "character" },
    { name: "female_human_1", url: "/images/characters/female-human.png", visual_type: "character" },
    { name: "female_human_2", url: "/images/characters/female-human-2.png", visual_type: "character" },
    { name: "female_elf_1", url: "/images/characters/female-elf.png", visual_type: "character" },
    { name: "female_elf_2", url: "/images/characters/female-elf-2.png", visual_type: "character" },
    { name: "vocation_warrior", url: "/images/characters/icon-vocation-warrior.svg", visual_type: "vocation" },
    { name: "vocation_vagabond", url: "/images/characters/icon-vocation-vagabond.svg", visual_type: "vocation" },
    { name: "vocation_physician", url: "/images/characters/icon-vocation-physician.svg", visual_type: "vocation" },
    { name: "vocation_scholar", url: "/images/characters/icon-vocation-scholar.svg", visual_type: "vocation" },
    { name: "element_null", url: "/images/game/icon-element-null.svg", visual_type: "element" },
    { name: "element_water", url: "/images/game/icon-element-water.svg", visual_type: "element" },
    { name: "element_earth", url: "/images/game/icon-element-earth.svg", visual_type: "element" },
    { name: "element_fire", url: "/images/game/icon-element-fire.svg", visual_type: "element" },
    { name: "element_air", url: "/images/game/icon-element-air.svg", visual_type: "element" },
    { name: "element_light", url: "/images/game/icon-element-light.svg", visual_type: "element" },
    { name: "element_darkness", url: "/images/game/icon-element-darkness.svg", visual_type: "element" },
    { name: "element_ice", url: "/images/game/icon-element-ice.svg", visual_type: "element" },
    { name: "element_lightning", url: "/images/game/icon-element-lightning.svg", visual_type: "element" },
    { name: "element_poison", url: "/images/game/icon-element-poison.svg", visual_type: "element" },

    { name: "item_hand_axe", url: "/images/item/icon-hand_axe.svg", visual_type: "item" },
    { name: "item_greataxe", url: "/images/item/icon-greataxe.svg", visual_type: "item" },
    { name: "item_staff", url: "/images/item/icon-staff.svg", visual_type: "item" },
    { name: "item_spear", url: "/images/item/icon-spear.svg", visual_type: "item" },
    { name: "item_halberd", url: "/images/item/icon-halberd.svg", visual_type: "item" },
    { name: "item_short_bow", url: "/images/item/icon-short_bow.svg", visual_type: "item" },
    { name: "item_long_bow", url: "/images/item/icon-long_bow.svg", visual_type: "item" },
    { name: "item_mandate_of_Heaven", url: "/images/item/icon-.svg", visual_type: "item" },
    { name: "item_potion_of_greater_healing", url: "/images/item/icon-potion_of_greater_healing.svg", visual_type: "item" },
    { name: "item_potion_of_healing", url: "/images/item/icon-potion_of_healing.svg", visual_type: "item" },
    { name: "item_herb", url: "/images/item/icon-herb.svg", visual_type: "item" },
    { name: "item_leather_cap", url: "/images/item/icon-leather_cap.svg", visual_type: "item" },
    { name: "item_dagger", url: "/images/item/icon-dagger.svg", visual_type: "item" },
    { name: "item_short_sword", url: "/images/item/icon-short_sword.svg", visual_type: "item" },
    { name: "item_longsword", url: "/images/item/icon-longsword.svg", visual_type: "item" },
    { name: "item_greatsword", url: "/images/item/icon-greatsword.svg", visual_type: "item" },
    { name: "item_mace", url: "/images/item/icon-mace.svg", visual_type: "item" },
    { name: "item_great_hammer", url: "/images/item/icon-great_hammer.svg", visual_type: "item" },
    { name: "item_light_helm", url: "/images/item/icon-light_helm.svg", visual_type: "item" },
    { name: "item_chain_coif", url: "/images/item/icon-chain_coif.svg", visual_type: "item" },
    { name: "item_plate_helm", url: "/images/item/icon-plate_helm.svg", visual_type: "item" },
    { name: "item_linen_cloth", url: "/images/item/icon-linen_cloth.svg", visual_type: "item" },
    { name: "item_leather_armor", url: "/images/item/icon-leather_armor.svg", visual_type: "item" },
    { name: "item_chain_mail_shirt", url: "/images/item/icon-chain_mail_shirt.svg", visual_type: "item" },
    { name: "item_scale_mail", url: "/images/item/icon-scale_mail.svg", visual_type: "item" },
    { name: "item_plate_mail", url: "/images/item/icon-plate_mail.svg", visual_type: "item" },
    { name: "item_buckler", url: "/images/item/icon-buckler.svg", visual_type: "item" },
    { name: "item_light_shield", url: "/images/item/icon-light_shield.svg", visual_type: "item" },
    { name: "item_kite_shield", url: "/images/item/icon-kite_shield.svg", visual_type: "item" },
    { name: "item_heavy_shield", url: "/images/item/icon-heavy_shield.svg", visual_type: "item" },
    { name: "item_tower_shield", url: "/images/item/icon-tower_shield.svg", visual_type: "item" },
    { name: "item_silver_ring", url: "/images/item/icon-silver_ring.svg", visual_type: "item" },
    { name: "item_gold_ring", url: "/images/item/icon-gold_ring.svg", visual_type: "item" },
    { name: "item_diamond_ring", url: "/images/item/icon-diamond_ring.svg", visual_type: "item" },
    { name: "item_panacea", url: "/images/item/icon-panacea.svg", visual_type: "item" },
]

images.each do |image|
    VisualRender.find_or_create_by!(image)
    puts "Created visual render: #{image[:name]}"
end

puts "Seeding Visual Renders completed!"