puts "Seeding Visual Renders..."

images = [
    { name: "icon_placeholder", url: "---" },
    { name: "male_human_1", url: "/images/characters/male-human.png", visual_type: "character" },
    { name: "male_human_2", url: "/images/characters/male-human-2.png", visual_type: "character" },
    { name: "male_human_3", url: "/images/characters/male-human-3.png", visual_type: "character" },
    { name: "male_dwarf_1", url: "/images/characters/male-dwarf.png", visual_type: "character" },
    { name: "male_elf_1", url: "/images/characters/male-elf.png", visual_type: "character" },
    { name: "male_orc_1", url: "/images/characters/male-orc.png", visual_type: "character" },
    { name: "female_human_1", url: "/images/characters/female-human.png", visual_type: "character" },
    { name: "female_human_2", url: "/images/characters/female-human-2.png", visual_type: "character" },
    { name: "female_elf_1", url: "/images/characters/female-elf.png", visual_type: "character" },
    { name: "female_elf_2", url: "/images/characters/female-elf-2.png", visual_type: "character" },
    { name: "vocation_warrior", url: "/images/characters/icon-vocation-warrior.svg", visual_type: "vocation" },
    { name: "vocation_vagabond", url: "/images/characters/icon-vocation-vagabond.svg", visual_type: "vocation" },
    { name: "vocation_physician", url: "/images/characters/icon-vocation-physician.svg", visual_type: "vocation" },
    { name: "vocation_scholar", url: "/images/characters/icon-vocation-scholar.svg", visual_type: "vocation" },
    { name: "element_null", url: "/images/game/icon-element-null.svg", visual_type: "element" },
    { name: "element_water", url: "/images/game/icon-element-water.svg", visual_type: "element" },
    { name: "element_earth", url: "/images/game/icon-element-earth.svg", visual_type: "element" },
    { name: "element_fire", url: "/images/game/icon-element-fire.svg", visual_type: "element" },
    { name: "element_air", url: "/images/game/icon-element-air.svg", visual_type: "element" },
    { name: "element_light", url: "/images/game/icon-element-light.svg", visual_type: "element" },
    { name: "element_darkness", url: "/images/game/icon-element-darkness.svg", visual_type: "element" },
    { name: "element_ice", url: "/images/game/icon-element-ice.svg", visual_type: "element" },
    { name: "element_lightning", url: "/images/game/icon-element-lightning.svg", visual_type: "element" },
    { name: "element_poison", url: "/images/game/icon-element-poison.svg", visual_type: "element" },

    { name: "item_hand_axe", url: "/images/item/icon-hand_axe.png", visual_type: "item" },
    { name: "item_greataxe", url: "/images/item/icon-greataxe.png", visual_type: "item" },
    { name: "item_staff", url: "/images/item/icon-staff.png", visual_type: "item" },
    { name: "item_spear", url: "/images/item/icon-spear.png", visual_type: "item" },
    { name: "item_halberd", url: "/images/item/icon-halberd.png", visual_type: "item" },
    { name: "item_short_bow", url: "/images/item/icon-short_bow.png", visual_type: "item" },
    { name: "item_long_bow", url: "/images/item/icon-long_bow.png", visual_type: "item" },
    { name: "item_mandate_of_Heaven", url: "/images/item/icon-.png", visual_type: "item" },
    { name: "item_potion_of_greater_healing", url: "/images/item/icon-potion_of_greater_healing.png", visual_type: "item" },
    { name: "item_potion_of_healing", url: "/images/item/icon-potion_of_healing.png", visual_type: "item" },
    { name: "item_herb", url: "/images/item/icon-herb.png", visual_type: "item" },
    { name: "item_leather_cap", url: "/images/item/icon-leather_cap.png", visual_type: "item" },
    { name: "item_dagger", url: "/images/item/icon-dagger.png", visual_type: "item" },
    { name: "item_short_sword", url: "/images/item/icon-short_sword.png", visual_type: "item" },
    { name: "item_longsword", url: "/images/item/icon-longsword.png", visual_type: "item" },
    { name: "item_greatsword", url: "/images/item/icon-greatsword.png", visual_type: "item" },
    { name: "item_mace", url: "/images/item/icon-mace.png", visual_type: "item" },
    { name: "item_great_hammer", url: "/images/item/icon-great_hammer.png", visual_type: "item" },
    { name: "item_light_helm", url: "/images/item/icon-light_helm.png", visual_type: "item" },
    { name: "item_chain_coif", url: "/images/item/icon-chain_coif.png", visual_type: "item" },
    { name: "item_plate_helm", url: "/images/item/icon-plate_helm.png", visual_type: "item" },
    { name: "item_linen_cloth", url: "/images/item/icon-linen_cloth.png", visual_type: "item" },
    { name: "item_leather_armor", url: "/images/item/icon-leather_armor.png", visual_type: "item" },
    { name: "item_chain_mail_shirt", url: "/images/item/icon-chain_mail_shirt.png", visual_type: "item" },
    { name: "item_scale_mail", url: "/images/item/icon-scale_mail.png", visual_type: "item" },
    { name: "item_plate_mail", url: "/images/item/icon-plate_mail.png", visual_type: "item" },
    { name: "item_buckler", url: "/images/item/icon-buckler.png", visual_type: "item" },
    { name: "item_light_shield", url: "/images/item/icon-light_shield.png", visual_type: "item" },
    { name: "item_kite_shield", url: "/images/item/icon-kite_shield.png", visual_type: "item" },
    { name: "item_heavy_shield", url: "/images/item/icon-heavy_shield.png", visual_type: "item" },
    { name: "item_tower_shield", url: "/images/item/icon-tower_shield.png", visual_type: "item" },
    { name: "item_silver_ring", url: "/images/item/icon-silver_ring.png", visual_type: "item" },
    { name: "item_gold_ring", url: "/images/item/icon-gold_ring.png", visual_type: "item" },
    { name: "item_diamond_ring", url: "/images/item/icon-diamond_ring.png", visual_type: "item" },
    { name: "item_panacea", url: "/images/item/icon-panacea.png", visual_type: "item" },

    { name: "monster_goblin", url: "/images/creatures/icon-goblin.png", visual_type: "monster" },
    { name: "monster_goblin_warrior", url: "/images/creatures/icon-goblin_warrior.png", visual_type: "monster" },
    { name: "monster_orc", url: "/images/creatures/icon-orc.png", visual_type: "monster" },
    { name: "monster_skeleton", url: "/images/creatures/icon-skeleton.png", visual_type: "monster" },
    { name: "monster_skeleton_warrior", url: "/images/creatures/icon-skeleton_warrior.png", visual_type: "monster" },
    { name: "monster_zombie", url: "/images/creatures/icon-zombie.png", visual_type: "monster" },
    { name: "monster_ghost", url: "/images/creatures/icon-ghost.png", visual_type: "monster" },
    { name: "monster_wolf", url: "/images/creatures/icon-wolf.png", visual_type: "monster" },
    { name: "monster_imp", url: "/images/creatures/icon-imp.png", visual_type: "monster" },
    { name: "monster_stone_golem", url: "/images/creatures/icon-stone_golem.png", visual_type: "monster" },
    { name: "monster_slime", url: "/images/creatures/icon-slime.png", visual_type: "monster" },
    { name: "monster_dragon", url: "/images/creatures/icon-dragon.png", visual_type: "monster" },
]

images.each do |image|
    VisualRender.find_or_create_by!(image)
    puts "Created visual render: #{image[:name]}"
end

puts "Seeding Visual Renders completed!"