name: Docker Image CI

on:
  push:
    branches: ["master"]

jobs:
  build-push-prod-image:
    runs-on: ubuntu-latest

    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push with commit hash tag
        run: docker compose build
      - name: Build and push with commit hash tag 2
        run: docker tag seventhforge lujw10/seventhforge:${{ steps.vars.outputs.sha_short }}
      - name: Build and push with commit hash tag 3
        run: docker push lujw10/seventhforge:${{ steps.vars.outputs.sha_short }}
